// <auto-generated />
namespace Swift.UI.Web.Mvc.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class DevTest : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(DevTest));
        
        string IMigrationMetadata.Id
        {
            get { return "201609161652173_DevTest"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
